### ISSUE TITLE
执行python manage.py crontab add报错，麻烦看一下，歇歇。

### ISSUE THREAD

**Issue by wangrui0435** [yueyongyue/saltshaker#37]
[root@saltstack-master-1 2.1.3]# python manage.py crontab add
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
  File "/usr/lib/python2.6/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/usr/lib/python2.6/site-packages/django/utils/version.py", line 7, in <module>
    from django.utils.lru_cache import lru_cache
  File "/usr/lib/python2.6/site-packages/django/utils/lru_cache.py", line 28
    fasttypes = {int, str, frozenset, type(None)},
                    ^
SyntaxError: invalid syntax

**Comment by orangefei** [comment]
我的也报错了，请问一下是怎么解决的呢。
如下：
TypeError: view must be a callable or a list/tuple in the case of include().
