### ISSUE TITLE
启动后网站可以登录，但是celery启动日志会一直报IOError

### ISSUE THREAD

**Issue by yang59324** [yueyongyue/saltshaker#40]
[2018-06-27 16:19:19,003: ERROR/MainProcess] Task shaker.tasks.minions_status_task[c9bb54de-6538-4ab2-b3c4-ddc736bb6a84] raised unexpected: IOError()
Traceback (most recent call last):
  File "/root/py27env/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/py27env/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cache/saltshaker/shaker/tasks.py", line 81, in minions_status_task
    sapi = SaltAPI()
  File "/cache/saltshaker/shaker/shaker_core.py", line 20, in __init__
    content = self.postRequest(obj, prefix='/login')
  File "/cache/saltshaker/shaker/shaker_core.py", line 29, in postRequest
    opener = urllib2.urlopen(req)
  File "/usr/local/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError

**Comment by qianxk** [comment]
我今天也遇到个IOError，HTTP unauthorized，后来发现是在机器层面新建admin用户时，没有给admin用户创建密码，导致saltapi在pam认证的时候，一直不成功。给admin用户创建密码以后，问题解决。可以执行命令：echo 'admin'|passwd --stdin admin
