### ISSUE TITLE
[Errno 2] No such file or directory: '/tmp/salt_dashboard.tmp'

### ISSUE THREAD

**Issue by Seka2701** [yueyongyue/saltshaker#9]
hi, 
we installed saltshaker with following commands: 

```
echo deb http://ppa.launchpad.net/saltstack/salt/ubuntu `lsb_release -sc` main | sudo tee /etc/apt/sources.list.d/saltstack.list

wget -q -O- "http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x4759FA960E27C0A6" | sudo apt-key add –

apt-get update

apt-get install salt-master salt-minion salt-syndic salt-api python-pip python-cherrypy3 mysql-server python-mysqldb

useradd -g admin admin && passwd admin
vim /etc/salt/master.d/saltapi.conf
     rest_cherrypy:
        port: 8000
        host: 127.0.0.1
        disable_ssl: true
     external_auth:
        pam:
          admin:
            - .*
            - '@runner'
            - '@wheel'

/etc/init.d/salt-master restart

/etc/init.d/salt-api restart

netstat -tnlp | grep 8000

cd /opt
pip install Django==1.8.4
git clone https://github.com/yueyongyue/saltshaker.git
cd /opt/saltshaker
vi saltshaker/settings.py
mysql -u root –p 

In mysql-shell: 
show databases;
create database saltshaker;
show databases;
create user saltshaker@localhost;
set password for saltshaker@localhost=password('saltshaker');
grant all on saltshaker.* to saltshaker@localhost;

mysql -u saltshaker –p
show databases;
use saltshaker;
quit

pip install django-crontab
python manage.py migrate
python manage.py runserver 0.0.0.0:9000&
python manage.py createsuperuser
```

---

by using the web-gui we can logg in but than following mistake returns:

```
IOError at /

[Errno 2] No such file or directory: '/tmp/salt_dashboard.tmp'

Request Method:     GET
Request URL:    http://192.168.0.11
Django Version:     1.8.4
Exception Type:     IOError
Exception Value:    

[Errno 2] No such file or directory: '/tmp/salt_dashboard.tmp'

Exception Location:     /opt/saltshaker/dashboard/views.py in index, line 12
Python Executable:  /usr/bin/python
Python Version:     2.7.6
Python Path:    

['/opt/saltshaker',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']

Server time:    Wed, 3 Feb 2016 12:45:29 +0100`
```

when we touch the missing file manually, following error message returns: 

```
`IndexError at /

list index out of range

Request Method:     GET
Request URL:    http://192.168.0.11/
Django Version:     1.8.4
Exception Type:     IndexError
Exception Value:    

list index out of range

Exception Location:     /opt/saltshaker/dashboard/views.py in index, line 14
Python Executable:  /usr/bin/python
Python Version:     2.7.6
Python Path:    

['/opt/saltshaker',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']

Server time:    Wed, 3 Feb 2016 12:29:48 +0100`
```

What´s wrong ? 

Best regards

**Comment by yueyongyue** [comment]
hi

# django-crontab

CRONJOBS = (
    ('*/1 \* \* \* *', 'shaker.cron.dashboard_scheduled_job'),
)
please execute command:
python manage.py crontab add

django-crontab will create /tmp/salt_dashboard.tmp file every minute.

**Comment by Seka2701** [comment]
We add the cronjob with your python comman but the file is not created. 
If we execute the command in the crontab we get an error 401: 

```
`# /usr/bin/python /opt/saltshaker/manage.py crontab run a69abdead75461c29e5d444fd9d79a91
Traceback (most recent call last):
  File "/opt/saltshaker/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django_crontab/management/commands/crontab.py", line 29, in handle
    Crontab().run_job(options['jobhash'])
  File "/usr/local/lib/python2.7/dist-packages/django_crontab/crontab.py", line 142, in run_job
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/saltshaker/shaker/cron.py", line 44, in <module>
    dashboard = dashboard_scheduled_job()
  File "/opt/saltshaker/shaker/cron.py", line 7, in dashboard_scheduled_job
    status = sapi.runner_status('status')
  File "/opt/saltshaker/shaker/shaker_core.py", line 151, in runner_status
    self.token_id()
  File "/opt/saltshaker/shaker/shaker_core.py", line 22, in token_id
    content = self.postRequest(obj, prefix='/login')
  File "/opt/saltshaker/shaker/shaker_core.py", line 31, in postRequest
    opener = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized
`
```

**Comment by yueyongyue** [comment]
hi !
HTTP Error 401: Unauthorized
You can check salt-api authentication.
/etc/salt/master.d/saltapi.conf ,There are strict format requirements.
see  https://github.com/yueyongyue/saltshaker/blob/master/saltapi.conf

**Comment by Seka2701** [comment]
This is how it looks like: 

```
rest_cherrypy:
  port: 8000
  host: 0.0.0.0
  disable_ssl: true
external_auth:
  pam:
    admin:
        - .*
        - '@runner'
        - '@wheel'
```

it doesn't work.

**Comment by Seka2701** [comment]
user name has to be saltapi: 

```
saltapi@salt-master:~$ cat /etc/salt/master.d/saltapi.conf
rest_cherrypy:
  port: 8000
  host: 0.0.0.0
  disable_ssl: true
external_auth:
  pam:
    saltapi:
        - .*
        - '@runner'
        - '@wheel'

```
